=== RomanFadeyev/DotNet/RailwayGis/KSPDIGT.FLC.Checker/Schema/flc.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (x64) (http://www.altova.com) by Same User (Ru-Board) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="FLC">
		<xs:annotation>
			<xs:documentation>Форматно-логический контроль файловой ГБД</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Version" type="xs:string">
					<xs:annotation>
						<xs:documentation>Версия проверямой ГБД</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Layers">
					<xs:annotation>
						<xs:documentation>Список слоев</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Layer" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Слой</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Name" type="xs:string">
											<xs:annotation>
												<xs:documentation>Наименование</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="Geometry">
											<xs:annotation>
												<xs:documentation>Тип геометрии</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="Polygon Features"/>
													<xs:enumeration value="Line Features"/>
													<xs:enumeration value="Point Features"/>
													<xs:enumeration value="Multipoint Features"/>
													<xs:enumeration value="MultiPatch Features"/>
													<xs:enumeration value="Dimension Features"/>
													<xs:enumeration value="Annotation Features"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="ZValues" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Наличие Z-координат</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:boolean">
														<xs:attribute name="MinZ" type="xs:double">
															<xs:annotation>
																<xs:documentation>Z мин</xs:documentation>
															</xs:annotation>
														</xs:attribute>
														<xs:attribute name="MaxZ" type="xs:double">
															<xs:annotation>
																<xs:documentation>Z макс</xs:documentation>
															</xs:annotation>
														</xs:attribute>
														<xs:attribute name="NaNZ" type="xs:double">
															<xs:annotation>
																<xs:documentation>Z недопустимое</xs:documentation>
															</xs:annotation>
														</xs:attribute>
														<xs:attribute name="MaxRake" type="xs:double">
															<xs:annotation>
																<xs:documentation>Z макс.уклон</xs:documentation>
															</xs:annotation>
														</xs:attribute>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="CheckSelfIntersect" type="xs:boolean" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Проверять самопересечение</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="NoCrossLayers" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Отсутствие пересечения с другими слоями</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Layer" type="xs:string" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Слой</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="CurvatureMinAngle" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Минимальный угол кривизны</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:minExclusive value="0"/>
													<xs:maxInclusive value="180"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="Checks" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Проверки на уровне слоя</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Check" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Проверка</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Name" type="xs:string">
																	<xs:annotation>
																		<xs:documentation>Наименование</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="JS" type="xs:string">
																	<xs:annotation>
																		<xs:documentation>Javascript code</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Fields">
											<xs:annotation>
												<xs:documentation>Список полей</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Field" maxOccurs="unbounded">
														<xs:annotation>
															<xs:documentation>Поле</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Name" type="xs:string">
																	<xs:annotation>
																		<xs:documentation>Наименование</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="Type">
																	<xs:annotation>
																		<xs:documentation>Тип</xs:documentation>
																	</xs:annotation>
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:enumeration value="Short Integer"/>
																			<xs:enumeration value="Long Integer"/>
																			<xs:enumeration value="Float"/>
																			<xs:enumeration value="Double"/>
																			<xs:enumeration value="Text"/>
																			<xs:enumeration value="Date"/>
																			<xs:enumeration value="Blob"/>
																			<xs:enumeration value="Guid"/>
																			<xs:enumeration value="Raster"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:element>
																<xs:element name="Length" type="xs:integer" minOccurs="0">
																	<xs:annotation>
																		<xs:documentation>Длина</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="Unique" type="xs:boolean" minOccurs="0">
																	<xs:annotation>
																		<xs:documentation>Уникальность</xs:documentation>
																	</xs:annotation>
																</xs:element>
																<xs:element name="References" minOccurs="0">
																	<xs:annotation>
																		<xs:documentation>Описание ссылочной целостности</xs:documentation>
																	</xs:annotation>
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="Reference" maxOccurs="unbounded">
																				<xs:annotation>
																					<xs:documentation>Ссылочная целостность</xs:documentation>
																				</xs:annotation>
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="ParentLayer" type="xs:string">
																							<xs:annotation>
																								<xs:documentation>Слой</xs:documentation>
																							</xs:annotation>
																						</xs:element>
																						<xs:element name="ParentField" type="xs:string">
																							<xs:annotation>
																								<xs:documentation>Столбец</xs:documentation>
																							</xs:annotation>
																						</xs:element>
																						<xs:element name="Cardinality">
																							<xs:annotation>
																								<xs:documentation>Мощность</xs:documentation>
																							</xs:annotation>
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="Min" type="xs:integer"/>
																									<xs:element name="Max" type="xs:integer" minOccurs="0">
																										<xs:annotation>
																											<xs:documentation>Если Max отсутствует, то предполагается unbound</xs:documentation>
																										</xs:annotation>
																									</xs:element>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="CheckRegExp" type="xs:string" minOccurs="0">
																	<xs:annotation>
																		<xs:documentation>Регулярное выражение для проверки</xs:documentation>
																	</xs:annotation>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="ExternalCheckers" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Внешние обработчики (DLL)</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ExternalChecker" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Внешний обработчик</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Assembly" type="xs:string">
											<xs:annotation>
												<xs:documentation>Наименование DLL</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="ClassName" type="xs:string">
											<xs:annotation>
												<xs:documentation>Наименование класса</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="CheckedByDefault" type="xs:boolean" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Помечено по-умолчанию</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== RomanFadeyev/DotNet/RailwayGis/SolutionFiles/CommonFiles/FLC.Checks.xml
<?xml version="1.0" encoding="UTF-8"?>
<FLC xsi:noNamespaceSchemaLocation="flc.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Version>2013.11.05</Version>
	<Layers>
		<Layer>
			<Name>pPk_p</Name>
			<Geometry>Point Features</Geometry>
			<ZValues>true</ZValues>
			<CheckSelfIntersect>false</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^010[23]000$</CheckRegExp>
				</Field>
				<Field>
					<Name>NUM</Name>
					<Type>Text</Type>
					<Length>255</Length>
					<CheckRegExp>^\d+/\d+$</CheckRegExp>
				</Field>
				<Field>
					<Name>ASUP_ID</Name>
					<Type>Long Integer</Type>
				</Field>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>pPOI_p</Name>
			<Geometry>Point Features</Geometry>
			<ZValues>false</ZValues>
			<CheckSelfIntersect>false</CheckSelfIntersect>
			<Checks>
				<Check>
					<Name>Для станции или перегона наименование д.б.заполнено</Name>
					<JS><![CDATA[(!(([KEY] ==1) && ([VALUE] == 1 || [VALUE] == 2) && ([NAME] == false)))]]></JS>
				</Check>
			</Checks>
			<Fields>
				<Field>
					<Name>KEY</Name>
					<Type>Short Integer</Type>
					<CheckRegExp>^[1-9]|10|11|12|13|14|15|16$</CheckRegExp>
				</Field>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>AXIS_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wAxes_l</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
							</Cardinality>
						</Reference>
					</References>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>VALUE</Name>
					<Type>Short Integer</Type>
				</Field>
				<Field>
					<Name>NAME</Name>
					<Type>Text</Type>
					<Length>255</Length>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wRails_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues MinZ="1" MaxZ="2000" MaxRake="200">true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<NoCrossLayers>
				<Layer>wPlatf_a</Layer>
				<Layer>wSettl_a</Layer>
				<Layer>wTower_a</Layer>
				<Layer>wTrLig_a</Layer>
			</NoCrossLayers>
			<CurvatureMinAngle>170</CurvatureMinAngle>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>NUM</Name>
					<Type>Text</Type>
					<CheckRegExp>^[01]$</CheckRegExp>
				</Field>
				<Field>
					<Name>ASUP_ID</Name>
					<Type>Long Integer</Type>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^050[23]000$</CheckRegExp>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>pSta_p</Name>
			<Geometry>Point Features</Geometry>
			<ZValues>false</ZValues>
			<CheckSelfIntersect>false</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0407000$</CheckRegExp>
				</Field>
				<Field>
					<Name>NAME</Name>
					<Type>Text</Type>
					<Length>255</Length>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>SIDE</Name>
					<Type>Short Integer</Type>
					<CheckRegExp>^[123]$</CheckRegExp>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wSurf_p</Name>
			<Geometry>Point Features</Geometry>
			<ZValues>true</ZValues>
			<CheckSelfIntersect>false</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0105000$</CheckRegExp>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wAxes_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues MinZ="1" MaxZ="2000" MaxRake="200">true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<NoCrossLayers>
				<Layer>wPlatf_a</Layer>
				<Layer>wSettl_a</Layer>
				<Layer>wTower_a</Layer>
				<Layer>wTrLig_a</Layer>
			</NoCrossLayers>
			<CurvatureMinAngle>170</CurvatureMinAngle>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0501000$</CheckRegExp>
				</Field>
				<Field>
					<Name>NUM</Name>
					<Type>Text</Type>
					<Length>255</Length>
				</Field>
				<Field>
					<Name>LEFT_RAIL_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wRails_l</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
							</Cardinality>
						</Reference>
					</References>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>RIGHT_RAIL_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wRails_l</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
							</Cardinality>
						</Reference>
					</References>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>WAY_TYPE</Name>
					<Type>Short Integer</Type>
					<CheckRegExp>^[1-9]|10|11|12|13|14|15|23$</CheckRegExp>
				</Field>
				<Field>
					<Name>ASUP_ID</Name>
					<Type>Long Integer</Type>
				</Field>
				<Field>
					<Name>BEGIN_AXIS_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wAxes_l</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
								<Max>1</Max>
							</Cardinality>
						</Reference>
					</References>
				</Field>
				<Field>
					<Name>END_AXIS_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wAxes_l</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
								<Max>1</Max>
							</Cardinality>
						</Reference>
					</References>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wAxesAux_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues>true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>DESCRIPTION</Name>
					<Type>Text</Type>
					<Length>255</Length>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wConst_a</Name>
			<Geometry>Polygon Features</Geometry>
			<ZValues MinZ="0" MaxZ="0">true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0901000|0902000|0903000|0904000|0905000|0906000|0908000|0910000|0911000|0514000$</CheckRegExp>
				</Field>
				<Field>
					<Name>ASUP_ID</Name>
					<Type>Long Integer</Type>
				</Field>
				<Field>
					<Name>ASUP_TYPE</Name>
					<Type>Short Integer</Type>
				</Field>
				<Field>
					<Name>ASUP_NAME</Name>
					<Type>Text</Type>
					<Length>50</Length>
				</Field>
				<Field>
					<Name>NAME</Name>
					<Type>Text</Type>
					<Length>255</Length>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wBridgeSpan_a</Name>
			<Geometry>Polygon Features</Geometry>
			<ZValues>true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0901000$</CheckRegExp>
				</Field>
				<Field>
					<Name>TYPE</Name>
					<Type>Short Integer</Type>
					<CheckRegExp>^[1-5]$</CheckRegExp>
				</Field>
				<Field>
					<Name>DRIVING</Name>
					<Type>Short Integer</Type>
					<CheckRegExp>^[12]?$</CheckRegExp>
				</Field>
				<Field>
					<Name>JOIN_GID</Name>
					<Type>Text</Type>
					<References>
						<Reference>
							<ParentLayer>wConst_a</ParentLayer>
							<ParentField>GID</ParentField>
							<Cardinality>
								<Min>0</Min>
							</Cardinality>
						</Reference>
					</References>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wCarW_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues MinZ="1" MaxZ="2000">true</ZValues>
			<CheckSelfIntersect>false</CheckSelfIntersect>			
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^1002000|1006000|1007000|1009000|1010000$</CheckRegExp>
				</Field>
			</Fields>
		</Layer>
		<Layer>
			<Name>wRelief_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues MinZ="1" MaxZ="2000">true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
					<Unique>true</Unique>
					<CheckRegExp>^.+$</CheckRegExp>
				</Field>
				<Field>
					<Name>CLS_TYPE</Name>
					<Type>Text</Type>
					<Length>50</Length>
					<CheckRegExp>^0504000|0505000|0506000|0509000|0510000$</CheckRegExp>
				</Field>	
			</Fields>
		</Layer>
		<Layer>
			<Name>wConW_l</Name>
			<Geometry>Line Features</Geometry>
			<ZValues MinZ="1" MaxZ="2000" MaxRake="1000">true</ZValues>
			<CheckSelfIntersect>true</CheckSelfIntersect>
			<CurvatureMinAngle>160</CurvatureMinAngle>
			<Fields>
				<Field>
					<Name>GID</Name>
					<Type>Text</Type>
